# Generated by Django 5.0.6 on 2024-06-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Успешно"), ("FAIL", "Неуспешно")],
                        max_length=50,
                        verbose_name="Статус отправки",
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ответ сервера"
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ф.И.О.")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                ("comments", models.TextField(verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_mailing", models.DateTimeField(verbose_name="Начало рассылки")),
                (
                    "end_mailing",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Конец рассылки"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("DAILY", "Ежедневно"),
                            ("WEEKLY", "Еженедельно"),
                            ("MONTHLY", "Ежемесячно"),
                        ],
                        max_length=30,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Создана"),
                            ("IN_PROGRESS", "В процессе"),
                            ("COMPLETED", "Завершена"),
                        ],
                        default="CREATED",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "permissions": [("set_completed", "Can complete mailing")],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100, verbose_name="Тема")),
                ("text", models.TextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
