# Generated by Django 5.0.6 on 2024-06-26 07:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Kлиент", "verbose_name_plural": "Kлиенты"},
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("set_completed", "Can complete mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="next_send_time",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="start_time",
        ),
        migrations.AddField(
            model_name="mailing",
            name="end_mailing",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Конец рассылки"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="start_mailing",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Начало рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="client",
            field=models.ManyToManyField(to="mail.client", verbose_name="Клиенты"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mail.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="regularity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "раз в день"),
                    ("weekly", "раз в неделю"),
                    ("monthly", "раз в месяц"),
                ],
                max_length=30,
                null=True,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создана"),
                    ("IN_PROGRESS", "В процессе"),
                    ("COMPLETED", "Завершена"),
                ],
                default="CREATED",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
    ]
