# Generated by Django 5.0.6 on 2024-06-27 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0004_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mail.client",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="attempt_date",
            field=models.DateTimeField(verbose_name="Дата отправки"),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[("SUCCESS", "Успешно"), ("FAIL", "Не успешно")],
                default="FAIL",
                max_length=50,
                verbose_name="Статус отправки",
            ),
        ),
    ]
