# Generated by Django 4.2 on 2024-07-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0006_alter_mailing_regularity_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_mailing",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Конец рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="mail.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="regularity",
            field=models.CharField(
                choices=[
                    ("Каждые 2 часа", "Каждые 2 часа"),
                    ("Ежедневно", "Ежедневно"),
                    ("Еженедельно", "Еженедельно"),
                    ("Ежемесечно", "Ежемесечно"),
                ],
                max_length=30,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_mailing",
            field=models.TimeField(verbose_name="начало рассылки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Активна", "Активна"),
                    ("Завершено", "Завершено"),
                ],
                default="created",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
    ]
