# Generated by Django 4.2 on 2024-07-05 20:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0007_alter_mailing_end_mailing_alter_mailing_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="end_mailing",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="start_mailing",
        ),
        migrations.AddField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 6, 20, 6, 9, 50558, tzinfo=datetime.timezone.utc
                ),
                verbose_name="конец рассылки",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="next_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="дата следующей рассылки",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="начало рассылки"
            ),
        ),
    ]
