# Generated by Django 4.2 on 2024-07-10 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0020_alter_mailing_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 11, 18, 45, 19, 468676, tzinfo=datetime.timezone.utc
                ),
                verbose_name="конец рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="next_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 10, 20, 45, 19, 468676, tzinfo=datetime.timezone.utc
                ),
                verbose_name="дата следующей рассылки",
            ),
        ),
    ]
